name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify your Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          if [ -f "package.json" ]; then
            npm install
          else
            echo "No package.json found. Skipping dependency installation."
          fi

      # Step 4: Run linting
      - name: Run linting
        run: |
          if [ -f "node_modules/.bin/eslint" ]; then
            npx eslint . || { echo "Linting failed."; exit 1; }
          else
            echo "ESLint not found. Skipping linting."
          fi

      # Step 5: Run tests
      - name: Run tests
        run: |
          if [ -f "node_modules/.bin/jest" ]; then
            npx jest --ci || { echo "Tests failed."; exit 1; }
          else
            echo "Jest not found. Skipping tests."
          fi

      # Step 6: Build the project
      - name: Build the project
        run: |
          if [ -f "package.json" ]; then
            npm run build || { echo "Build failed."; exit 1; }
          else
            echo "No package.json found. Skipping build."
          fi

      # Step 7: Docker build and test
      - name: Build and test Docker image
        if: exists('Dockerfile')
        run: |
          docker build -t my-app:latest . || { echo "Docker build failed."; exit 1; }
          docker run --rm my-app:latest || { echo "Docker container test failed."; exit 1; }

      # Step 8: Cleanup
      - name: Cleanup
        run: |
          rm -rf node_modules
