name: Docker Pull and Deploy

on:
  push:

env:
  DOCKER_USERNAME: rukevweubio
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  docker_image: nginx
  docker_registry: docker.io

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Docker login
      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login ${{ env.docker_registry }} --username ${{ env.DOCKER_USERNAME }} --password-stdin

      # Step 2: Pull Docker image
      - name: Pull Docker image
        run: docker pull ${{ env.docker_registry }}/${{ env.DOCKER_USERNAME }}/${{ env.docker_image }}:latest

      # Step 3: Deploy the Docker container
      - name: Deploy Docker container
        run: |
          docker run -d -p 80:80 ${{ env.docker_registry }}/${{ env.DOCKER_USERNAME }}/${{ env.docker_image }}:latest
