name: Docker Build and Push

on:
  push:
   
env:
    DOCKER_USERNAME: rukevweubio
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    docker_image: nginx
    docker_registry: docker.io
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${{ env.docker_registry }}/${{ env.DOCKER_USERNAME }}/{{ env.docker_image }} .

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login ${{ env.docker_registry }} --username ${{ env.DOCKER_USERNAME }} --password-stdin

      - name: Docker pull image
        run: docker pull ${{ env.docker_registry }}/${{ env.DOCKER_USERNAME }}/{{ env.docker_image }}:latest
deploy:
  needs: docker
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Docker Hub
      run: |
        
        docker run -d -p 80:80 ${{ env.docker_registry }}/${{env.DOCKER_USERNAME}}/docker_image:latest    