name: Docker Build and Push

on:
  push:

env:
  DOCKER_USERNAME: rukevweubio
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  docker_image: nginx
  docker_registry: docker.io

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ env.docker_registry }}/${{ env.DOCKER_USERNAME }}/${{ env.docker_image }} .

      # Step 3: Docker login
      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login ${{ env.docker_registry }} --username ${{ env.DOCKER_USERNAME }} --password-stdin

      # Step 4: Push Docker image
      - name: Push Docker image
        run: docker push ${{ env.docker_registry }}/${{ env.DOCKER_USERNAME }}/${{ env.docker_image }}:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy to Docker Hub
      - name: Deploy to Docker Hub
        run: |
          docker run -d -p 80:80 ${{ env.docker_registry }}/${{ env.DOCKER_USERNAME }}/${{ env.docker_image }}
