name: Docker Build and Push

on:
  push:
   
env:
    DOCKER_USERNAME: rukevweubio
    DOCKER_PASSWORD: Comfort12345@
    docker_image: nginx
    docker_registry: docker.io
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: build docker image
        uses: docker build -t ${{env.docker_registry}}/${{env.DOCKER_USERNAME}}/docker_image .

      - name: docker login 
        uses: docker login ${{secrets.DOCKER_PASSWORD}}| --username=${{env.OCKER_USERNAME}} --password-stdin  

      - name: docker pull image 
        uses: docker pull ${{env.Ddocker_registry}}/${{env.DOCKER_USERNAME}}/docker_image:latest
deploy:
  needs: docker
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Docker Hub
      run: |
        
        docker run -d -p 80:80 ${{ env.docker_registry }}/${{env.DOCKER_USERNAME}}/docker_image:latest    