name: Build, Push, and Deploy Docker Image

on:
  push:
    

env:
  DOCKER_USERNAME: rukevweubio
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  docker_image: mongo
  docker_registry: docker.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Docker login
      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login ${{ env.docker_registry }} --username ${{ env.DOCKER_USERNAME }} --password-stdin

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ env.docker_registry }}/${{ env.DOCKER_USERNAME }}/${{ env.docker_image }}:latest .github/workflows/

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ env.docker_registry }}/${{ env.DOCKER_USERNAME }}/${{ env.docker_image }}:latest

  pull-and-deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    

    steps:
      # Step 1: Docker login
      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login ${{ env.docker_registry }} --username ${{ env.DOCKER_USERNAME }} --password-stdin

      # Step 2: Pull the Docker image from Docker Hub
      - name: Pull Docker image
        run: docker pull ${{ env.docker_registry }}/${{ env.DOCKER_USERNAME }}/${{ env.docker_image }}:latest

      # Step 3: Run the Docker container
      - name: Deploy Docker container
        run: |
          docker run -d -p 27017:27017 ${{ env.docker_registry }}/${{ env.DOCKER_USERNAME }}/${{ env.docker_image }}:latest
