name: matrix job-configuration
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: docker run hello world

      - name: Install dependencies
        run:  docker info

  deploy:
    runs-on: windows-latest
    steps:
      - name:  deploy on window
        run: docker run hello world 

      - name: Build
        run: docker run hello world

      - name: shell
        run: |

          docker info

        

    
 