name: Matrix Config

on:
  push:

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [hello-world, alpine]

    runs-on: ${{ matrix.os }}
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run a test container
      - name: Run a test container
        run: docker run ${{ matrix.node-version }}

      # Step 3: Display Docker information
      - name: Display Docker information
        run: docker info 